version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing jq...
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      - echo Logging into DockerHub...
      - export SECRET=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query SecretString --output text)
      - export DOCKER_USERNAME=$(echo $SECRET | jq -r .username)
      - export DOCKER_PASSWORD=$(echo $SECRET | jq -r .password)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t application:$IMAGE_TAG .

  post_build:
    commands:
      - echo Tagging and pushing Docker image to Amazon ECR...
      - docker tag application:$IMAGE_TAG 992382459149.dkr.ecr.us-east-1.amazonaws.com/application:$IMAGE_TAG
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker push 992382459149.dkr.ecr.us-east-1.amazonaws.com/application:$IMAGE_TAG
      - echo Build completed on `date`
